# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Felipe Campelo
subtitle: Random ramblings from a not-so-mad (data) scientist
email: fcampelo@gmail.com
description: Random ramblings from a not-so-mad (data) scientist.#>- # this means to ignore newlines until "baseurl:"
twitter_username: "_fcampelo"
github_username: "fcampelo"
google_analytics: "UA-17267347-2"
minimal_mistakes_skin: "neon"
search: true

# Build settings
markdown: kramdown
remote_theme: fcampelo/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Felipe Campelo"
  avatar : "/assets/images/profile_500px.png"
  bio    : "Data Science + Optimisation."
  links:
    - label: "Me @Aston University"
      icon: "fas fa-fw fa-link"
      url: "https://research.aston.ac.uk/en/persons/felipe-campelo-franca-pinto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_fcampelo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fcampelo"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com.br/citations?hl=en&user=jKGZEXIAAAAJ&view_op=list_works&sortby=pubdate"

footer:
  links:
    - label: "Me @Aston University"
      icon: "fas fa-fw fa-link"
      url: "https://research.aston.ac.uk/en/persons/felipe-campelo-franca-pinto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_fcampelo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fcampelo"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com.br/citations?hl=en&user=jKGZEXIAAAAJ&view_op=list_works&sortby=pubdate"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
